# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Timezone
timezone: Europe/Stockholm

title: CLASP
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The Centre For Linguistics Theory and Studies in Propability
#baseurl:  # the subpath of your site, e.g. /blog
domain: gu-clasp.github.io
url: "https://gu-clasp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: NONE
#github_username:

future: true

plugins:
  - jekyll-feed

source: ./
destination: ./_site


collections:
  people:
    output: true
  events:
    output: true
  news:
    output: true
  pages:
    output: true
    permalink: /:path

include: ['_pages']

# layout defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  -
    scope:
      path: ""
      type: "people"
    values:
      layout: "person"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
