name: Refresh

on:
  schedule:
    - cron:  '0 13 * * *' # Runs every day at 3am (testing auto-build at 13.00)

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $NIGHTLY_REBUILD_TOKEN_AILOMAA" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/GU-CLASP/GU-CLASP.github.io/pages/builds
